### ISSUE TITLE
uninitialized constant DelayedJobSequel

### ISSUE THREAD

**Issue by TSMMark** [TalentBox/delayed_job_sequel#8]
```
/var/lib/gems/2.1.0/gems/talentbox-delayed_job_sequel-4.3.0/lib/delayed/backend/sequel.rb:7:in `<module:Sequel>': uninitialized constant DelayedJobSequel (NameError)
from /var/lib/gems/2.1.0/gems/talentbox-delayed_job_sequel-4.3.0/lib/delayed/backend/sequel.rb:4:in `<module:Backend>'
from /var/lib/gems/2.1.0/gems/talentbox-delayed_job_sequel-4.3.0/lib/delayed/backend/sequel.rb:3:in `<module:Delayed>'
from /var/lib/gems/2.1.0/gems/talentbox-delayed_job_sequel-4.3.0/lib/delayed/backend/sequel.rb:2:in `<top (required)>'
from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
from /var/lib/gems/2.1.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:67:in `backend='
```

**Comment by TSMMark** [comment]
Am I doing something wrong?

**Comment by TSMMark** [comment]
resolved by manually requiring this library in the initializer

```
require "delayed_job_sequel"
::Delayed::Worker.backend = :sequel
```
